# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(879, 834)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(320, 10, 271, 81))
        self.label.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 75 28pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 160, 301, 51))
        self.label_2.setStyleSheet("color:rgb(85, 0, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 250, 331, 51))
        self.label_3.setStyleSheet("color:rgb(85, 0, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.Divpush = QtWidgets.QPushButton(Form)
        self.Divpush.setGeometry(QtCore.QRect(170, 450, 112, 81))
        self.Divpush.setObjectName("Divpush")
        self.Addpush = QtWidgets.QPushButton(Form)
        self.Addpush.setGeometry(QtCore.QRect(360, 330, 112, 81))
        self.Addpush.setObjectName("Addpush")
        self.Subpush = QtWidgets.QPushButton(Form)
        self.Subpush.setGeometry(QtCore.QRect(550, 450, 112, 81))
        self.Subpush.setObjectName("Subpush")
        self.Mulpush = QtWidgets.QPushButton(Form)
        self.Mulpush.setGeometry(QtCore.QRect(360, 590, 112, 81))
        self.Mulpush.setObjectName("Mulpush")
        self.Result = QtWidgets.QLabel(Form)
        self.Result.setGeometry(QtCore.QRect(370, 460, 121, 81))
        self.Result.setStyleSheet("color:rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.Result.setObjectName("Result")
        self.firstnumber = QtWidgets.QLineEdit(Form)
        self.firstnumber.setGeometry(QtCore.QRect(420, 150, 131, 51))
        self.firstnumber.setObjectName("firstnumber")
        self.Secondnumber = QtWidgets.QLineEdit(Form)
        self.Secondnumber.setGeometry(QtCore.QRect(420, 240, 131, 51))
        self.Secondnumber.setObjectName("Secondnumber")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Calculator"))
        self.label_2.setText(_translate("Form", "Enter the First Number:"))
        self.label_3.setText(_translate("Form", "Enter the Second Number:"))
        self.Divpush.setText(_translate("Form", "DIV"))
        self.Addpush.setText(_translate("Form", "ADD"))
        self.Subpush.setText(_translate("Form", "SUB"))
        self.Mulpush.setText(_translate("Form", "MUL"))
        self.Result.setText(_translate("Form", "Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
